<?php
	/**
	 * Project: MVC2022.
	 * Author:  InCubics
	 * Date:    30/06/2022
	 * File:    index.phtml
	 */
?>
	<h2>index FruitY</h2>
	Actions in FruitY are made as Eloquent alike queries build with model-methods<br>
	All queries made with MySqli with bind-params<br>
	<hr>
	<a href="<?= url('/fruity_add'.getQsa()) ?>">add <i class="bi bi-plus darkblue"></i></a>
	&emsp;
	<a href="<?= url() ?>"?>home <i class="bi bi-house-door-fill darkblue"></i></a>
	<!-- https://icons.getbootstrap.com -->
	<table class="indextable">
	<?php
		
		if(!empty($data))
		{
			echo '<tr><th class="tableHead120">fruitname</th><th class="tableHead120">color</th><th></th><th></th></tr>';
			foreach($data as $row)
			{
				echo '<tr>';
				echo '<td class="leftCel">'.$row->name.'</td>';
				echo '<td>'.$row->color.'</td>';
				echo '<td> <a href="'.url('/fruity_update/'.$row->id.getQsa()).'">
								<i class="bi bi-pen-fill darkblue"></i>
							</a> </td>';
				echo '<td class="rightCel"> <a href="'.url('/fruity_delete/'.$row->id.getQsa()).'">
							<i class="bi bi-trash3-fill text-danger"></i>
						</a> </td>';
				echo '</tr>';
			}
		}
		else	{
			echo 'no records found';
		}
	?>
		<ul>
			<?php
				foreach( $arrayMessages  as $messages) {
					foreach($messages as $type =>  $message )
					{echo '<li class="text-'.$type.'">Message: '.$message.'</li>';}
				}
			?>
		</ul>
	</table>
	<?= $pagination ?>
