<?php
	/**
	 * Project: MVC2022.
	 * Author:  InCubics
	 * Date:    29/06/2022
	 * Updated: 02/10/2025
	 * File:    show.phtml
	 */
?>
<h2>
	<?= $title ?> SHOW - 2
</h2>
<br>
<a href="<?= url('/articles')?>">articles index</a><br>
<hr>
<?= $string ?><br>
The ID in the url as param0 (p0) is: <b><?= ($id ? $id : 'not provided as url-param') ?></b>
<br><br>
Data by id from given array; <b><i><?= $data ?></i></b>
<hr>
<h3>Some query-examples in this MVC-framework</h3>
Eloquent-alike data-queries;<br><br>
<li><b>Some example queries</b></li>
<ul>
	<li>(new Fruit())->all()->get();
	<li>(new Fruit())->all()->limit(3,4)->get();
	<li> (new Fruit())->select()->all()->pagination(5)->get();
	<li>(new Fruit())->find(25)->get();  	&emsp;// id 25 must exist
	<li>(new Fruit())->select(['name','color'], )->orderby(['name', 'color'])->get();
	<li>(new Fruit())->select()->orderby(['name', 'color'])->get();
	<li>(new Fruit())->select()->orderby('name')->get();
	<li>(new Fruit())->select()->orderby(['name', 'color|DESC'])->get());
	<li>(new Fruit())->select()->orderby(['name|DESC', 'color|ASC'])->get());
	<li>(new Fruit())->select(['name','color'], true)->where('sweetness', 1)->get()); 		$emsp; // distinct on true and specific selection of fieldnames
	<li>((new Fruit())->raw('SELECT * FROM `fruits` WHERE `id` = ?', ['id'=> 25]))->meta; 	&emsp; // meta-info on raw-query with bind-params on data-array
	<li>(new Fruit())->select()->where('sweetness', 1)->get();
	<li>(new Fruit())->select(['avg'=>'sweetness',<br>
			&emsp;'sum'=> 'sweetness',<br>
			&emsp;'min'=> 'sweetness',<br>
			&emsp;'max'=> 'sweetness',<br>
			'count'=> 'id'])->where('color', 'yellow')->get();   &emsp;// aggregate examples <br>
	<li>(new Fruit())->select(['color','sweetness'], true)->where('color', 'green')->get();
	<li>(new Fruit())->all()->toJson()->get();
</ul>
<li><b>Relations</b></li>
	<ul>
		<li>(new User())->select()->oneOnMany('id','user_id','users_fruits')->get();
		<li>(new User())->select()->oneOnMany('id','user_id','users_fruits')->toNested()->get();
		<li>(new User())->select()->manyOnMany('Fruit')->get();
		<li>(new User())->select()->manyOnMany('Fruit')->toNested()->get();
		<li>(new User())->select()->manyOnMany('Fruit')->toNested()->toJson()->get();
		<li>(new User())->select()->manyOnMany('Fruit')->get();
	</ul>
<li><b>API solution</b></li>
	<ul>
	<li>http://mvc2025.rk/api/token</li>
		<ul>
			<li>get a JWT token</li>
			<li>stores token in table `users` of given user-data</li>
			<li>submitted password is hidden in json-response</li>
			<li>method: POST, values: [username =>'aadmin@app.com', password='password'] </li>
		</ul>
		<li>http://mvc2025.rk/api/fruit</li>
		<ul>
			<li>gets all record of table `fruits`, only fillable-fields</li>
		</ul>
	<li>http://mvc2025.rk/api/user</li>
		<ul>
			<li>gets all record of table `fruits`</li>
			<li>only fillable-fields and without hidden-fields</li>
		</ul>
	<li>http://mvc2025.rk/api/fruit/6</li>
		<ul>
			<li>find id 6 of table `fruits`</li>
		</ul>
		<li>http://mvc2025.rk/api/fruit/first</li>
		<ul>
			<li>finds first record of table `fruits`</li>
		</ul>
	<li>http://mvc2025.rk/api/fruit?page=2</li>
		<ul>
			<li>page 2 paginated of table `fruits`</li>
			<li>amount by param or config.ini</li>
		</ul>
	<li>http://mvc2025.rk/api/fruit/add</li>
		<ul>
			<li>adds a record to table `fruits`</li>
			<li>requires token in header-key: <token>, depending in Middleware-route</li>
			<li>method: POST, values: [name =>'Starfruit', color='light yellow', sweetness='1'] </li>
		</ul>
		<li>http://mvc2025.rk/api/fruit/update/3</li>
			<ul>
				<li>updates record with id 3 of table `fruits`</li>
				<li>requires token in header-key: <token>, depending in Middleware-route</li>
				<li>method: post, values: [_method=>'PUT', name =>'Starfruit', color='light yellow', sweetness='1'] </li>
				<li>get-values: [p2 => 3]</li>
			</ul>
		<li>http://mvc2025.rk/api/fruit/delete/3</li>
			<ul>
				<li>updates record with id 3 of table `fruits`</li>
				<li>requires token in header-key: <token>, depending in Middleware-route</li>
				<li>method: post, post-values: [_method=>'DELETE']</li>
				<li>get-values: [p2 => 3]</li>
			</ul>
	</ul>
</ul>

