<?php
	/**
	 * Project: MVC2022.
	 * Author:  InCubics
	 * Date:    29/06/2022
	 * File:    index.phtml
	 */
?>
	<h2>index Fruit</h2>
	Actions in Fruit are made with simple MySqli-queries.<br>
	See 'fruity' (menu-bar) for queries with bind-params<br>
	<hr>
	<a href="<?= url('/fruit_add'.getQsa()) ?>">add <i class="bi bi-plus darkblue"></i></a>
	&emsp;
	<a href="<?= url() ?>"?>home <i class="bi bi-house-door-fill darkblue"></i></a>
	<!-- https://icons.getbootstrap.com -->
	<table class="indextable">
	<?php
		if(count((array)$data) > 0)
		{
			echo '<tr><th class="tableHead120">fruitname</th><th></th><th></th></tr>';
			foreach($data as $row)
			{
				echo '<tr>';
				echo '<td class="leftCel">'.$row->name.'</td>';
				echo '<td><a href="'.url('/fruit_update/'.$row->id.getQsa()).'">
							<i class="bi bi-pen-fill darkblue"></i>
							</a> </td>';
				echo '<td class="rightCel"><a href="'.url('/fruit_delete/'.$row->id.getQsa()).'">
							<i class="bi bi-trash3-fill text-danger"></i>
							</a> </td>';
				echo '</tr>';
			}
		}
		else	{
			echo 'no records found';
		}
	?>
	</table>
