<?php
	/**
	 * Project: MVC2022.
	 * Author:  InCubics
	 * Date:    29/06/2022
	 * File:    layout.phtml
	 */
?>
<!DOCTYPE html>
<html lang="<?= $meta->html_lang ?>">
<head>
	<title><?= $this->config->sitename ?> | <?= $meta->title ?></title>
	
	<meta charset="<?= $meta->char_set ?>">
	<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
	<!--	<meta charset="<?= $meta->char_set ?>>"/>-->
	<meta http-equiv="Content-Type" content="text/html; charset=<?= $meta->char_set ?>">
	<meta name="description" content="<?= $meta->description ?> "/>
	<meta name="keywords" content="<?= $meta->keywords ?>"/>
	<meta http-equiv=”content-language” content=”<?= $meta->language ?>”/>
	<meta name="author" content="<?= $meta->author ?>" />
	<meta name="copyright" content="<?= $meta->author ?>" />
	<meta name="robots" content="<?= $meta->robot ?>"/>
	<!--	<meta http-equiv="cache-control" content="no-cache"/>-->
	<!--	<meta http-equiv="expires" content="exercise date in seconds"/> <!--in seconds-->
	
	<?= $css ?>
</head>
<body>
<h1><?= $this->config->sitename ?></h1>
	<h2>MVC ++ default-layout</h2>
	<nav>
		<?= $nav ?>
	</nav>
	<hr>
    <article>
 		<?= $this->view() ?>
    </article>
	<p class="author">(c)<?= date('Y')?> by InCubics.net</p>
	<?= $js ?>
</body>
</html>
