<?php
	/**
	 * Project: MVC2022.
	 * Author:  InCubics
	 * Date:    29/06/2022
	 * Update:  01/10/2025
	 * File:    layout.phtml
	 */
?>

<!doctype html>
<html lang="<?= $meta->html_lang ?>">
<!--[if lt IE 7]>      <html class="no-js lt-ie9 lt-ie8 lt-ie7" lang=""> <![endif]-->
<!--[if IE 7]>         <html class="no-js lt-ie9 lt-ie8" lang=""> <![endif]-->
<!--[if IE 8]>         <html class="no-js lt-ie9" lang=""> <![endif]-->
<!--[if gt IE 8]><!--> <html class="no-js" lang=""> <!--<![endif]-->
<head>
	<meta charset="utf-8">
	<title><?= env('app')->name ?> | <?= $meta->title ?></title>
	<!-- <link rel="icon" type="image/x-icon" href="/favicon.ico">
	<link rel="shortcut icon" type="image/x-icon" href="/favicon.ico"> -->
	<link rel="icon" type="image/png" href="/favicon.png">


	<meta charset="<?= $meta->char_set ?>" />
	<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />
	<!--	<meta charset="<?= $meta->char_set ?>>" />-->
	<meta http-equiv="Content-Type" content="text/html; charset=<?= $meta->char_set ?>" />
	<meta name="description" content="<?= $meta->description ?>"/>
	<meta name="keywords" content="<?= $meta->keywords ?>"/>
	<meta http-equiv=”content-language” content="<?= $meta->language ?>"/>
	<meta name="author" content="<?= $meta->author ?>" />
	<meta name="copyright" content="<?= $meta->author ?>" />
	<meta name="robots" content="<?= $meta->robot ?>"/>
	<!--	<meta http-equiv="cache-control" content="no-cache"/>-->
	<!--	<meta http-equiv="expires" content="exercise date in seconds"/> <!--in seconds-->
	
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<link rel="apple-touch-icon" href="apple-touch-icon.png">
	
	<link rel="stylesheet" href="<?= url('css/bootstrap.min.css')?>">
	<style>
		body {
			padding-top: 50px;
			padding-bottom: 20px;
		}
	</style>
	<!-- rendered by a Service -->
	<?= $css ?>	<!-- rendered by a Service -->
<!--	<link rel="stylesheet" href="http://mvc2022.rk/css/bootstrap-theme.min.css">-->
<!--	<link rel="stylesheet" href="http://mvc2022.rk/css/main.css">-->
	
	<script src="http://mvc2022.rk/js/vendor/modernizr-2.8.3-respond-1.4.2.min.js"></script>
	
	
</head>
<body>
<!--[if lt IE 8]>
<p class="browserupgrade">You are using an <strong>outdated</strong> browser. Please <a href="http://browsehappy.com/">upgrade your browser</a> to improve your experience.</p>
<![endif]-->
<?php //include('../app/views/components/messagebar.phtml'); ?>
<?php echo yieldView('components.messagebar'); ?>


<nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">

	<div class="container">
		<a class="navbar-brand" href="#">
			<i class="bi bi-filetype-php font-weight-bold darkblue"></i>
			<?= env('app')->sitename ?>
		</a>
		<div class="navbar-header">
			<button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
				<span class="sr-only">Toggle navigation</span>
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
			</button>
		</div>
		<div id="navbar" class="navbar-collapse collapse">
			<?= $nav ?> 	<!-- rendered by a Service -->
		</div><!--/.navbar-collapse -->
	</div>
</nav>
<!-- Main jumbotron for a primary marketing message or call to action -->
<div class="jumbotron">
	<div class="container">
		<?= $this->view() ?>
	</div>
</div>

<div class="container">
	<!-- Example row of columns -->
	<div class="row">
		<div class="col-md-4">
			<h3>Heading 1</h3>
			<p>Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Etiam porta sem malesuada magna mollis euismod. Donec sed odio dui. </p>
			<!--			<p><a class="btn btn-default" href="#" role="button">View details &raquo;</a></p>-->
		</div>
		<div class="col-md-4">
			<h3>Heading 2</h3>
			<p>Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Etiam porta sem malesuada magna mollis euismod. Donec sed odio dui. </p>
			<!--			<p><a class="btn btn-default" href="#" role="button">View details &raquo;</a></p>-->
		</div>
		<div class="col-md-4">
			<h3>Heading 3</h3>
			<p>Donec sed odio dui. Cras justo odio, dapibus ac facilisis in, egestas eget quam. Vestibulum id ligula porta felis euismod semper. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus.</p>
			<!--			<p><a class="btn btn-default" href="#" role="button">View details &raquo;</a></p>-->
		</div>
	</div>
	
	<hr>
	
	<footer>
		<p class="author">&copy;<?= date('Y').'-'.(date('Y')+1)?> by <?= env('app')->author?></p>
	</footer>
</div> <!-- /container -->        <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.11.2/jquery.min.js"></script>
<script>window.jQuery || document.write('<script src="http://mvc2022.rk/js/vendor/jquery-1.11.2.min.js"><\/script>')</script>

<script src="<?= url('js/vendor/bootstrap.min.js')?>"></script>

<script src="<?= url('js/main.js')?>"></script>

<!-- Google Analytics: change UA-XXXXX-X to be your site's ID. -->
<!--<script>-->
<!--	(function(b,o,i,l,e,r){b.GoogleAnalyticsObject=l;b[l]||(b[l]=-->
<!--		function(){(b[l].q=b[l].q||[]).push(arguments)});b[l].l=+new Date;-->
<!--		e=o.createElement(i);r=o.getElementsByTagName(i)[0];-->
<!--		e.src='//www.google-analytics.com/analytics.js';-->
<!--		r.parentNode.insertBefore(e,r)}(window,document,'script','ga'));-->
<!--	ga('create','UA-XXXXX-X','auto');ga('send','pageview');-->
<!--</script>-->
</body>
</html>
