<?php
	/**
	 * Project: MVC2022.
	 * Author:  InCubics
	 * Date:    30/06/2022
	 * File:    show.phtml
	 */
	
	if(empty(session_get('login')))
	{		?>
		<h2>Login</h2>
		<form action="<?= url('/login') ?>" method="post">
			<?= csrf() ?>
			<input type="text" name="username" placeholder="username"
				   class="<?= ( $failMessages->username ) ? 'bg-danger ' : '' ?>"><br>
			<input type="password" name="password" placeholder="password"
				   class="<?= ( $failMessages->password ) ? 'bg-danger ' : '' ?>"><br>
			<input type="submit" name="submit" value="LOGIN">
		</form>
		<a href="<?= url('/forgot')?>">forgot password</a>
		<?php if(isset($msg)) { echo $msg; } ?>
		<ul>
			<?php
				foreach( $failMessages  as $fails) {
					foreach($fails as $fail )
					{echo '<li class="text-danger">'.$fail.'</li>';}
				}
			?>
		</ul>
<?php
	}
	else
	{		?>
		<h2>Logoff</h2>
		<form action="<?= url('/login') ?>" method="post">
			<?=  csrf() ?>
			<input type="submit" name="logoff" value="LOGOFF">
		</form>
		<a href="<?= url('/renew')?>">renew password</a>

<?php
	}
